import type { Driver, Field, Implement, Job, JobType, Organization, Subtask, TaskTemplate, Vehicle } from "../types";

export const farmer = "Hof Müller";
export const contractor = "Agrarservice Schneider";

export const organizations: Organization[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    name: "Hof Müller",
    kind: "farmer",
    address: "Mühlenweg 4, 23900 Beispielhof",
    street: "Mühlenweg 4",
    country: "Deutschland",
    postalCode: "23900",
    city: "Beispielhof",
    phone: "+49 4541 12345",
    email: "info@hof-mueller.example",
    contacts: [{ id: "oc-1", name: "Bernd Müller", role: "Betriebsleiter", mobile: "+49 171 1234567", email: "bernd@hof-mueller.example", sms: "+49 171 1234567" }],
  },
  { id: "33333333-3333-4333-8333-333333333333", name: "Hof Andersson", kind: "farmer", address: "Skiftesvägen 12, 247 00 Södra Sandby, Schweden", street: "Skiftesvägen 12", country: "Schweden", postalCode: "247 00", city: "Södra Sandby", email: "kontakt@hof-andersson.example", contacts: [] },
  {
    id: "22222222-2222-4222-8222-222222222222",
    name: "Agrarservice Schneider",
    kind: "contractor",
    address: "Gewerbepark 8, 23900 Ratzeburg",
    street: "Gewerbepark 8",
    country: "Deutschland",
    postalCode: "23900",
    city: "Ratzeburg",
    phone: "+49 4541 98765",
    email: "dispo@agrarservice-schneider.example",
    contacts: [{ id: "oc-2", name: "Anna Schneider", role: "Einsatzleitung", mobile: "+49 172 9876543", email: "anna@agrarservice-schneider.example", sms: "+49 172 9876543" }],
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    name: "Lohnunternehmen Klos",
    kind: "contractor",
    address: "Kolaretorp, Schweden",
    street: "",
    country: "Schweden",
    postalCode: "",
    city: "Kolaretorp",
    email: "bernd@kolaretorp.se",
    contacts: [{ id: "oc-5", name: "Bernd Kolaretorp", role: "Einsatzleitung", mobile: "", email: "bernd@kolaretorp.se", sms: "" }],
  },
  { id: "44444444-4444-4444-8444-444444444444", name: "Lohnbetrieb Nord", kind: "contractor", address: "Transportvägen 3, 245 00 Staffanstorp, Schweden", street: "Transportvägen 3", country: "Schweden", postalCode: "245 00", city: "Staffanstorp", email: "info@lohnbetrieb-nord.example", contacts: [] },
];

export const drivers: Driver[] = [
  { id: "d1", organizationId: "22222222-2222-4222-8222-222222222222", name: "Max", email: "max@schlaglink.app", accessPassword: "schlaglink-demo", vehicle: "Fendt 724", jobVisibility: "contractor_all", mobile: "+46 70 111 22 33", licenseClasses: ["B", "T", "CE"], maxDailyHours: 10, resourceType: "Personal", operationType: "Gülle" },
  { id: "d2", organizationId: "22222222-2222-4222-8222-222222222222", name: "Jens", email: "jens@schlaglink.app", accessPassword: "schlaglink-demo", vehicle: "John Deere 6250R", jobVisibility: "assigned_only", mobile: "+46 70 222 33 44", licenseClasses: ["B", "T", "CE"], maxDailyHours: 9, resourceType: "Personal", operationType: "Gülle" },
  { id: "d3", organizationId: "22222222-2222-4222-8222-222222222222", name: "Lisa", email: "lisa@schlaglink.app", accessPassword: "schlaglink-demo", vehicle: "Claas Jaguar 950", jobVisibility: "assigned_only", mobile: "+46 70 333 44 55", licenseClasses: ["B", "T"], maxDailyHours: 8, resourceType: "Personal", operationType: "Grünland" },
  { id: "d4", organizationId: "22222222-2222-4222-8222-222222222222", name: "Tom", email: "tom@schlaglink.app", accessPassword: "schlaglink-demo", vehicle: "John Deere 6250R", jobVisibility: "assigned_only", mobile: "+46 70 444 55 66", licenseClasses: ["B", "T"], maxDailyHours: 8, resourceType: "Personal", operationType: "Saat" },
  { id: "d5", organizationId: "22222222-2222-4222-8222-222222222222", name: "Olof", email: "olof@schlaglink.app", accessPassword: "schlaglink-demo", vehicle: "MAN Agrar-LKW", jobVisibility: "contractor_all", mobile: "+46 70 555 66 77", licenseClasses: ["B", "T", "CE"], maxDailyHours: 9, resourceType: "Personal", operationType: "Transport" },
  { id: "d6", organizationId: "11111111-1111-4111-8111-111111111111", name: "Tobias", email: "tobias@schlaglink.app", accessPassword: "schlaglink-demo", vehicle: "Hofschlepper Müller", jobVisibility: "organization_internal", mobile: "+49 171 666 77 88", licenseClasses: ["B", "T"], maxDailyHours: 8, resourceType: "Personal", operationType: "Eigenmechanisierung" },
];

export const vehicles: Vehicle[] = [
  { id: "v0", organizationId: "11111111-1111-4111-8111-111111111111", name: "Hofschlepper Müller", type: "Schlepper", licensePlate: "RZ HM 125", resourceType: "Zugmaschine", operationType: "Hofarbeiten/Transport", status: "frei" },
  { id: "v1", organizationId: "22222222-2222-4222-8222-222222222222", name: "Fendt 724", type: "Schlepper", licensePlate: "SLA 724", resourceType: "Zugmaschine", operationType: "Gülle/Transport", status: "zugewiesen" },
  { id: "v2", organizationId: "22222222-2222-4222-8222-222222222222", name: "John Deere 6250R", type: "Schlepper", licensePlate: "SLA 250", resourceType: "Zugmaschine", operationType: "Gülle/Saat", status: "zugewiesen" },
  { id: "v3", organizationId: "22222222-2222-4222-8222-222222222222", name: "Claas Jaguar 950", type: "Häcksler", licensePlate: "SLA 950", resourceType: "Selbstfahrer", operationType: "Häckseln", status: "frei" },
  { id: "v4", organizationId: "22222222-2222-4222-8222-222222222222", name: "MAN Agrar-LKW", type: "Transport", licensePlate: "SLA 480", resourceType: "Transportfahrzeug", operationType: "Abfahren", status: "frei" },
  { id: "v5", organizationId: "22222222-2222-4222-8222-222222222222", name: "Valtra N175", type: "Schlepper", licensePlate: "SLA 175", resourceType: "Zugmaschine", operationType: "Reserve", status: "wartung" },
];

export const implementsList: Implement[] = [
  { id: "i1", organizationId: "22222222-2222-4222-8222-222222222222", name: "Güllefass 1", type: "Gülletechnik", resourceType: "Anbaugerät", operationType: "Gülle ausbringen", status: "zugewiesen" },
  { id: "i2", organizationId: "22222222-2222-4222-8222-222222222222", name: "Güllefass 2", type: "Gülletechnik", resourceType: "Anbaugerät", operationType: "Gülle ausbringen", status: "zugewiesen" },
  { id: "i3", organizationId: "22222222-2222-4222-8222-222222222222", name: "Sämaschine 6 m", type: "Sätechnik", resourceType: "Anbaugerät", operationType: "Säen", status: "frei" },
  { id: "i4", organizationId: "22222222-2222-4222-8222-222222222222", name: "Mähwerk Kombi", type: "Grünland", resourceType: "Anbaugerät", operationType: "Mähen", status: "frei" },
  { id: "i5", organizationId: "22222222-2222-4222-8222-222222222222", name: "Silowalze", type: "Silo", resourceType: "Anbaugerät", operationType: "Walzen", status: "frei" },
];

export const taskTemplates: TaskTemplate[] = [
  { id: "task-slurry", name: "Gülle ausbringen", workSteps: ["Anfahrt", "Ausbringen", "Fuhren dokumentieren"], timePerHa: 0.38, mode: "Teammodus", maxVehicles: 2, progressMetric: "Menge", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Schlepper mit Güllefass", unit: "m³" },
  { id: "task-manure", name: "Mist ausbringen", workSteps: ["Laden", "Ausbringen", "Randbereiche prüfen"], timePerHa: 0.45, mode: "Teammodus", maxVehicles: 2, progressMetric: "Menge", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Streuerkolonne", unit: "t" },
  { id: "task-sowing", name: "Säen", workSteps: ["Saatgut prüfen", "Säen", "Ablagetiefe kontrollieren"], timePerHa: 0.3, mode: "Einzelmodus", maxVehicles: 1, progressMetric: "Fläche", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Schlepper mit Sämaschine", unit: "ha" },
  { id: "task-rolling", name: "Walzen", workSteps: ["Walzen", "Vorgewende prüfen"], timePerHa: 0.18, mode: "Teammodus", maxVehicles: 2, progressMetric: "Zeit", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Walzschlepper", unit: "h" },
  { id: "task-cultivating", name: "Grubbern", workSteps: ["Grubbern", "Problemstellen melden"], timePerHa: 0.42, mode: "Einzelmodus", maxVehicles: 1, progressMetric: "Fläche", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Bodenbearbeitung", unit: "ha" },
  { id: "task-mowing", name: "Mähen", workSteps: ["Mähen", "Vorgewende mähen"], timePerHa: 0.28, mode: "Einzelmodus", maxVehicles: 1, progressMetric: "Fläche", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Mähkombination", unit: "ha", mapStyle: { label: "Gemäht", color: "#9be37d", pattern: "none" } },
  { id: "task-raking", name: "Schwaden", workSteps: ["Schwaden", "Schwadqualität prüfen"], timePerHa: 0.22, mode: "Einzelmodus", maxVehicles: 1, progressMetric: "Fläche", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Schwader", unit: "ha", mapStyle: { label: "Geschwadert", color: "#1f6b3a", pattern: "none" } },
  { id: "task-chopping", name: "Häckseln", workSteps: ["Häckseln", "Abfahrer koordinieren"], timePerHa: 0.55, mode: "Rollenmodus", maxVehicles: 2, progressMetric: "Zeit", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 0, resourceHint: "Häcksler", unit: "h" },
  { id: "task-hauling", name: "Abfahren", workSteps: ["Laden", "Transport", "Abladen"], timePerHa: 0.7, mode: "Teammodus", maxVehicles: 4, progressMetric: "Fuhren", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Abfahrgespann", unit: "Fuhren" },
  { id: "task-lime", name: "Kalk streuen", workSteps: ["Streumenge prüfen", "Streuen"], timePerHa: 0.25, mode: "Teammodus", maxVehicles: 2, progressMetric: "Menge", requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Streuer", unit: "t" },
];

export const jobTypes: JobType[] = [
  {
    id: "jt-slurry",
    name: "Gülle ausbringen",
    description: "Standardauftrag für Gülle mit Fasskolonnen und Fortschritt nach Menge/Fuhren.",
    defaultCrews: 2,
    defaultEstimatedHours: 7,
    resourceSummary: "Je Kolonne: 1 Fahrer, 1 Schlepper, 1 Güllefass",
    tasks: [
      {
        id: "jt-slurry-task",
        name: "Gülle ausbringen",
        mode: "Teammodus",
        allowMultipleWorkers: true,
        maxVehicles: 2,
        progressMetric: ["Menge", "Fuhren"],
        requiredDrivers: 1,
        requiredVehicles: 1,
        requiredImplements: 1,
        resourceHint: "Schlepper mit Güllefass",
        estimatedHours: 7,
        timePerHa: 0.38,
        plannedAmount: 25,
        targetValue: 25,
        unit: "m³/ha",
      },
    ],
  },
  {
    id: "jt-corn-sowing",
    name: "Mais säen",
    description: "Einzelmaschine je Fläche, Fortschritt nach ha.",
    defaultCrews: 1,
    defaultEstimatedHours: 5,
    resourceSummary: "1 Fahrer, 1 Schlepper, 1 Sämaschine",
    tasks: [
      {
        id: "jt-corn-sowing-task",
        name: "Mais säen",
        mode: "Einzelmodus",
        allowMultipleWorkers: false,
        maxVehicles: 1,
        progressMetric: ["Fläche"],
        requiredDrivers: 1,
        requiredVehicles: 1,
        requiredImplements: 1,
        resourceHint: "Schlepper mit Sämaschine",
        estimatedHours: 5,
        timePerHa: 0.3,
        unit: "ha",
      },
    ],
  },
  {
    id: "jt-grass-silage",
    name: "Grassilage",
    description: "Mehrstufige Grünlandkette mit optional mehreren Kolonnen beim Abfahren.",
    defaultCrews: 2,
    defaultEstimatedHours: 12,
    resourceSummary: "Mäh-/Schwadkolonne plus Abfahrkolonnen",
    tasks: [
      { id: "jt-grass-mow", name: "Mähen", mode: "Einzelmodus", allowMultipleWorkers: false, maxVehicles: 1, progressMetric: ["Fläche"], requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Mähkombination", estimatedHours: 2, timePerHa: 0.28, unit: "ha", mapStyle: { label: "Gemäht", color: "#9be37d", pattern: "none" } },
      { id: "jt-grass-rake", name: "Schwaden", mode: "Einzelmodus", allowMultipleWorkers: false, maxVehicles: 1, progressMetric: ["Fläche"], requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Schwader", estimatedHours: 2, timePerHa: 0.22, unit: "ha", mapStyle: { label: "Geschwadert", color: "#1f6b3a", pattern: "none" } },
      { id: "jt-grass-chop", name: "Häckseln", mode: "Rollenmodus", allowMultipleWorkers: true, maxVehicles: 2, progressMetric: ["Zeit"], requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 0, resourceHint: "Häcksler", estimatedHours: 3, timePerHa: 0.55, unit: "h" },
      { id: "jt-grass-haul", name: "Abfahren", mode: "Teammodus", allowMultipleWorkers: true, maxVehicles: 4, progressMetric: ["Fuhren", "Zeit"], requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Abfahrgespann", estimatedHours: 4, timePerHa: 0.7, unit: "Fuhren" },
      { id: "jt-grass-roll", name: "Walzen", mode: "Teammodus", allowMultipleWorkers: true, maxVehicles: 2, progressMetric: ["Zeit"], requiredDrivers: 1, requiredVehicles: 1, requiredImplements: 1, resourceHint: "Walzschlepper", estimatedHours: 1, timePerHa: 0.18, unit: "h" },
    ],
  },
];

export const fields: Field[] = [
  {
    id: "f1",
    organizationId: "11111111-1111-4111-8111-111111111111",
    name: "Nordfeld 1",
    areaHa: 8.4,
    crop: "Mais",
    tenure: "Eigentum",
    center: { lat: 55.72572, lng: 13.17942 },
    accessPoint: { lat: 55.72498, lng: 13.17792, label: "Westliches Tor am Feldweg" },
    accessDescription: "Von der Hofstelle Richtung Norden fahren, nach 800 m links in den Feldweg. Zufahrt über das westliche Tor.",
    boundary: [
      { lat: 55.72658, lng: 13.17782 },
      { lat: 55.72705, lng: 13.18108 },
      { lat: 55.72554, lng: 13.18182 },
      { lat: 55.72454, lng: 13.17972 },
      { lat: 55.72486, lng: 13.17756 },
    ],
    hazards: [
      {
        id: "h1",
        type: "wet_area",
        title: "Nasse Ecke Südwest",
        description: "Bei nassem Wetter nur mit leerer Maschine oder großem Bogen befahren.",
        location: { lat: 55.72478, lng: 13.1781 },
      },
    ],
    attachments: [
      { id: "a1", name: "Zufahrt Westtor Foto", kind: "photo" },
      { id: "a2", name: "Pachtkarte Nordfeld 1", kind: "document" },
    ],
    restrictedZones: ["Südwest-Ecke bei Regen meiden"],
    history: ["2025: Zwischenfrucht", "2026: Gülle geplant", "2026: Mais geplant"],
    releasedContractorIds: ["22222222-2222-4222-8222-222222222222"],
  },
  {
    id: "f2",
    organizationId: "11111111-1111-4111-8111-111111111111",
    name: "Nordfeld 2",
    areaHa: 6.2,
    crop: "Mais",
    tenure: "Pacht",
    center: { lat: 55.72904, lng: 13.18423 },
    accessPoint: { lat: 55.72818, lng: 13.18282, label: "Enge Zufahrt Südwest" },
    accessDescription: "Vom nördlichen Wirtschaftsweg kommend langsam in die enge Zufahrt einbiegen. Große Gespanne nacheinander einweisen.",
    boundary: [
      { lat: 55.72992, lng: 13.18258 },
      { lat: 55.73028, lng: 13.1857 },
      { lat: 55.7287, lng: 13.18614 },
      { lat: 55.72792, lng: 13.1842 },
      { lat: 55.7283, lng: 13.18274 },
    ],
    hazards: [
      {
        id: "h2",
        type: "narrow_access",
        title: "Enge Zufahrt",
        description: "Güllefässer einzeln einfahren lassen, Gegenverkehr vermeiden.",
        location: { lat: 55.72822, lng: 13.1829 },
      },
    ],
    attachments: [],
    restrictedZones: ["Nicht am Wohnhaus wenden"],
    history: ["2025: Pflügen", "2026: Saatbett vorbereitet"],
    releasedContractorIds: ["22222222-2222-4222-8222-222222222222"],
  },
  {
    id: "f3",
    organizationId: "11111111-1111-4111-8111-111111111111",
    name: "Hofacker",
    areaHa: 11.8,
    crop: "Weizen",
    tenure: "Eigentum",
    center: { lat: 55.71936, lng: 13.17152 },
    accessPoint: { lat: 55.72008, lng: 13.17002, label: "Hofzufahrt Nordkante" },
    accessDescription: "Direkt vom Hof Richtung Westen fahren und an der Nordkante einfahren. Randstreifen mit Steinen beachten.",
    boundary: [
      { lat: 55.72032, lng: 13.16942 },
      { lat: 55.72102, lng: 13.17306 },
      { lat: 55.71862, lng: 13.17414 },
      { lat: 55.71782, lng: 13.17122 },
      { lat: 55.7189, lng: 13.16912 },
    ],
    hazards: [
      {
        id: "h3",
        type: "stones",
        title: "Steine am Rand",
        description: "Nordwestlichen Rand langsam bearbeiten, größere Steine sichtbar.",
        location: { lat: 55.72012, lng: 13.16972 },
      },
    ],
    attachments: [],
    restrictedZones: [],
    history: ["2025: Weizen gedrillt", "2026: Düngung offen"],
    releasedContractorIds: ["22222222-2222-4222-8222-222222222222"],
  },
  {
    id: "f4",
    organizationId: "11111111-1111-4111-8111-111111111111",
    name: "Wiese am Bach",
    areaHa: 3.1,
    crop: "Gras",
    tenure: "Pacht",
    center: { lat: 55.7162, lng: 13.18758 },
    accessPoint: { lat: 55.71562, lng: 13.18656, label: "Brücke am Bach" },
    accessDescription: "Über die schmale Brücke am Bach zufahren. Gewässerabstand einhalten und nur leichte Gespanne nutzen.",
    boundary: [
      { lat: 55.71692, lng: 13.18642 },
      { lat: 55.71712, lng: 13.18862 },
      { lat: 55.71572, lng: 13.18904 },
      { lat: 55.71508, lng: 13.1873 },
      { lat: 55.71562, lng: 13.18634 },
    ],
    hazards: [
      {
        id: "h4",
        type: "water_protection",
        title: "Gewässerabstand",
        description: "Zum Bachlauf mindestens 5 m Abstand halten.",
        location: { lat: 55.71558, lng: 13.18704 },
      },
    ],
    attachments: [],
    restrictedZones: ["Bachkante nicht befahren"],
    history: ["2025: 3 Schnitte", "2026: Erster Schnitt geplant"],
    releasedContractorIds: ["22222222-2222-4222-8222-222222222222"],
  },
  {
    id: "f5",
    organizationId: "11111111-1111-4111-8111-111111111111",
    name: "Südacker",
    areaHa: 14.5,
    crop: "Raps",
    tenure: "Eigentum",
    center: { lat: 55.70958, lng: 13.17682 },
    accessPoint: { lat: 55.70912, lng: 13.17982, label: "Feldweg Ost" },
    accessDescription: "Nicht über den Hof Schmidt fahren. Zufahrt nur über Feldweg Ost, bei Regen Tragfähigkeit prüfen.",
    boundary: [
      { lat: 55.71092, lng: 13.17452 },
      { lat: 55.71134, lng: 13.17898 },
      { lat: 55.70872, lng: 13.18004 },
      { lat: 55.70786, lng: 13.17632 },
      { lat: 55.70908, lng: 13.17372 },
    ],
    hazards: [
      {
        id: "h5",
        type: "other",
        title: "Weicher Feldweg",
        description: "Feldweg Ost ist nach Starkregen weich, Fahrspuren dokumentieren.",
        location: { lat: 55.70922, lng: 13.17948 },
      },
    ],
    attachments: [],
    restrictedZones: ["Keine Durchfahrt Hof Schmidt"],
    history: ["2025: Raps gedrillt", "2026: Kontrollfahrt erledigt"],
    releasedContractorIds: [],
  },
];

export const jobs: Job[] = [
  {
    id: "j1",
    jobNumber: "A-001",
    title: "Gülle ausbringen",
    customer: farmer,
    contractor,
    fieldIds: ["f1", "f2", "f3"],
    timeWindow: "18.06.2026, 07:00 bis 20.06.2026, 18:00",
    notes: "25 m³/ha. Nasse Stellen langsam anfahren, Randbereiche sauber dokumentieren.",
    tasks: [
      {
        id: "t1",
        name: "Gülle ausbringen",
        mode: "Teammodus",
        allowMultipleWorkers: true,
        maxVehicles: 2,
        progressMetric: ["Menge", "Fuhren"],
        targetValue: 660,
        plannedAmount: 25,
        unit: "m³",
        estimatedHours: 7,
        timePerHa: 0.38,
      },
    ],
  },
  {
    id: "j2",
    jobNumber: "A-002",
    title: "Mais säen",
    customer: farmer,
    contractor,
    fieldIds: ["f1", "f2"],
    timeWindow: "21.06.2026, 06:00 bis 21.06.2026, 16:00",
    notes: "Saatfenster nutzen, Reihenabstand und Ablagetiefe nach Hofvorgabe.",
    tasks: [
      {
        id: "t2",
        name: "Mais säen",
        mode: "Einzelmodus",
        allowMultipleWorkers: false,
        maxVehicles: 1,
        progressMetric: ["Fläche"],
        targetValue: 14.6,
        unit: "ha",
        estimatedHours: 5,
        timePerHa: 0.3,
      },
    ],
  },
  {
    id: "j3",
    jobNumber: "A-003",
    title: "Grassilage Wiese am Bach",
    customer: farmer,
    contractor,
    fieldIds: ["f4"],
    timeWindow: "24.06.2026, 09:00 bis 25.06.2026, 20:00",
    notes: "Gewässerabstand beachten, Feuchtestellen markieren.",
    tasks: [
      { id: "t3", name: "Mähen", mode: "Einzelmodus", allowMultipleWorkers: false, maxVehicles: 1, progressMetric: ["Fläche"], targetValue: 3.1, unit: "ha", estimatedHours: 2, timePerHa: 0.28, mapStyle: { label: "Gemäht", color: "#9be37d", pattern: "none" } },
      { id: "t4", name: "Wenden", mode: "Einzelmodus", allowMultipleWorkers: false, maxVehicles: 1, progressMetric: ["Fläche"], targetValue: 3.1, unit: "ha", estimatedHours: 2, timePerHa: 0.2 },
      { id: "t5", name: "Schwaden", mode: "Einzelmodus", allowMultipleWorkers: false, maxVehicles: 1, progressMetric: ["Fläche"], targetValue: 3.1, unit: "ha", estimatedHours: 2, timePerHa: 0.22, mapStyle: { label: "Geschwadert", color: "#1f6b3a", pattern: "none" } },
      { id: "t6", name: "Häckseln", mode: "Rollenmodus", allowMultipleWorkers: true, maxVehicles: 2, progressMetric: ["Zeit"], targetValue: 2, unit: "h", estimatedHours: 3, timePerHa: 0.55 },
      { id: "t7", name: "Abfahren", mode: "Teammodus", allowMultipleWorkers: true, maxVehicles: 3, progressMetric: ["Fuhren", "Zeit"], targetValue: 14, unit: "Fuhren", estimatedHours: 4, timePerHa: 0.7 },
      { id: "t8", name: "Walzen", mode: "Teammodus", allowMultipleWorkers: true, maxVehicles: 2, progressMetric: ["Zeit"], targetValue: 2, unit: "h", estimatedHours: 1, timePerHa: 0.18 },
    ],
  },
];

export const subtasks: Subtask[] = [
  { id: "s1", jobId: "j1", fieldId: "f1", taskId: "t1", status: "in Arbeit", progress: 45, activeDriverIds: ["d1", "d2"], activeVehicleIds: ["v1", "v2"], activeImplementIds: ["i1", "i2"], targetValue: 210, targetUnit: "m³", doneAmount: 88, trips: 7, accessUsed: "Westliches Tor am Feldweg", accessOk: true },
  { id: "s2", jobId: "j1", fieldId: "f2", taskId: "t1", status: "reserviert", progress: 10, activeDriverIds: ["d2"], activeVehicleIds: ["v2"], activeImplementIds: ["i2"], targetValue: 155, targetUnit: "m³", doneAmount: 16, trips: 1, accessUsed: "Enge Zufahrt Südwest", accessOk: false },
  { id: "s3", jobId: "j1", fieldId: "f3", taskId: "t1", status: "offen", progress: 0, activeDriverIds: [], targetValue: 295, targetUnit: "m³" },
  { id: "s4", jobId: "j2", fieldId: "f1", taskId: "t2", status: "offen", progress: 0, activeDriverIds: [], targetValue: 8.4, targetUnit: "ha" },
  { id: "s5", jobId: "j2", fieldId: "f2", taskId: "t2", status: "Problem", progress: 0, activeDriverIds: [], note: "Saatgut noch nicht am Feld.", accessUsed: "Enge Zufahrt Südwest", accessOk: true },
  { id: "s6", jobId: "j3", fieldId: "f4", taskId: "t3", status: "erledigt", progress: 100, activeDriverIds: ["d3"], activeVehicleIds: ["v1"], activeImplementIds: ["i4"], doneHa: 3.1, accessUsed: "Brücke am Bach", accessOk: true },
  { id: "s7", jobId: "j3", fieldId: "f4", taskId: "t4", status: "teilweise erledigt", progress: 55, activeDriverIds: ["d3"], activeVehicleIds: ["v1"], doneHa: 1.7, accessUsed: "Brücke am Bach", accessOk: true, newHazardReported: true },
  { id: "s8", jobId: "j3", fieldId: "f4", taskId: "t5", status: "offen", progress: 0, activeDriverIds: [] },
  { id: "s9", jobId: "j3", fieldId: "f4", taskId: "t6", status: "offen", progress: 0, activeDriverIds: [] },
  { id: "s10", jobId: "j3", fieldId: "f4", taskId: "t7", status: "offen", progress: 0, activeDriverIds: [] },
  { id: "s11", jobId: "j3", fieldId: "f4", taskId: "t8", status: "offen", progress: 0, activeDriverIds: [] },
];
